{"title": "Manchester United vs Arsenal: Three key battles ahead of the Old Trafford showdown", "category": "Sport", "date": "4 years ago", "summary": "Manchester United would entertain Arsenal on Sunday as hostilities ensue between both sides in the Premier League. The clash would see both EPL giants do battle...", "image_url": "https://dailypost.ng/wp-content/uploads/2019/12/Manchester-united-Man-U-vs-Arsenal-400x240.jpg", "source": "https://dailypost.ng/2020/10/"}
{"title": "EPL: How Manchester United could line-up against Arsenal on Sunday", "category": "Sport", "date": "4 years ago", "summary": "Manchester United returns to the Premier League with a home game against Arsenal just like German side RB Leipzig visited Old Trafford in the midweek, although...", "image_url": "https://dailypost.ng/wp-content/uploads/2020/07/manchester-united-c-flag-400x240.jpg", "source": "https://dailypost.ng/2020/10/"}
{"title": "Sanwo-Olu directs all civil servants to resume November 2", "category": "News", "date": "4 years ago", "summary": "The Governor of Lagos state, Babajide Sanwo-Olu, has directed all public servants on Salary Grade Levels 1- 12, to resume work fully from Monday, November 2,...", "image_url": "https://dailypost.ng/wp-content/uploads/2020/01/Sanwo-Olu-_-400x240.jpg", "source": "https://dailypost.ng/2020/10/"}
{"title": "Nigerian govt states position on social media regulation", "category": "News", "date": "4 years ago", "summary": "The Federal Government says it has no intention of shutting down social media. The Minister of Information and Culture, Alhaji Lai Mohammed, made the clarification on...", "image_url": "https://dailypost.ng/wp-content/uploads/2020/08/Lai-Mohammed-400x240.jpg", "source": "https://dailypost.ng/2020/10/"}
{"title": "ManU vs Arsenal: Possible line-up of Arteta\u2019s men for Sunday\u2019s clash", "category": "Sport", "date": "4 years ago", "summary": "Arsenal would take on Ole Gunnar Solskjaer\u2019s men on Sunday afternoon with just two points adrift of them (Red Devils) in the Premier League table. The...", "image_url": "https://dailypost.ng/wp-content/uploads/2020/10/Arteta-400x240.jpg", "source": "https://dailypost.ng/2020/10/"}
{"title": "Auto crash claims over 10 lives in Ondo [Photos]", "category": "Metro", "date": "4 years ago", "summary": "More than 10 persons lost their lives in Ondo State on Saturday night in an accident that occurred in Akungba-Akoko, Akoko South West Local Government of...", "image_url": "https://dailypost.ng/wp-content/uploads/2020/10/IMG-20201031-WA0005-400x240.jpg", "source": "https://dailypost.ng/2020/10/"}
{"title": "Gov Sanwo-Olu lifts curfew in Lagos with immediate effect", "category": "News", "date": "4 years ago", "summary": "The Governor of Lagos state, Babajide Sanwo-Olu, has lifted the curfew imposed on the state with immediate effect. This was contained in a press release signed...", "image_url": "https://dailypost.ng/wp-content/uploads/2020/04/Lagos-Governor-400x240.jpg", "source": "https://dailypost.ng/2020/10/"}
{"title": "Nigeria\u2019s power generation hits all-time peak of 5,520MW", "category": "News", "date": "4 years ago", "summary": "Nigeria\u2019s power sector has recorded another national peak generation of 5,520.40MW. Ndidi Mbah, General Manager, Public Affairs division of the Transmission Company of Nigeria (TCN) confirmed...", "image_url": "https://dailypost.ng/wp-content/uploads/2019/08/Transmission-Company-of-Nigeria-TCN-400x240.jpg", "source": "https://dailypost.ng/2020/10/"}
{"title": "Gov. Fayemi  advocates for restructuring, proffers solution to Nigeria\u2019s  problems", "category": "News", "date": "4 years ago", "summary": "The Chairman, Nigerian Governors\u2019 Forum and Governor of Ekiti State, Dr. Kayode Fayemi says there is a need for the recreation of Nigeria to satisfy restructuring...", "image_url": "https://dailypost.ng/wp-content/uploads/2020/08/Fayemi-e1555964703785-400x240.jpg", "source": "https://dailypost.ng/2020/10/"}
{"title": "Survival Fund: Nigerian govt announces new website", "category": "News", "date": "4 years ago", "summary": "The Federal Government has announced a new portal for the Macro, Small and Medium Enterprises (MSMEs) Survival Fund and Guaranteed off-take Stimulus Scheme. The website will...", "image_url": "https://dailypost.ng/wp-content/uploads/2020/09/Mariam-Katagum-400x240.jpg", "source": "https://dailypost.ng/2020/10/"}
{"title": "Man Utd vs Arsenal: Aubameyang opens up on lack of goals", "category": "Sport", "date": "4 years ago", "summary": "Arsenal captain, Pierre-Emerick Aubameyang, has expressed his confidence that he will rediscover his goalscoring form again. Aubameyang has gone five Premier League matches without scoring. It...", "image_url": "https://dailypost.ng/wp-content/uploads/2020/03/Aubameyang-400x240.jpg", "source": "https://dailypost.ng/2020/10/"}
{"title": "It is over \u2013 Guardiola takes final decision on leaving for Barcelona", "category": "Sport", "date": "4 years ago", "summary": "Manchester City manager, Pep Guardiola, has insisted his time at Barcelona is \u201cover\u201d. Guardiola stated this on Saturday, after a 1-0 win at Sheffield United in...", "image_url": "https://dailypost.ng/wp-content/uploads/2019/12/Guardiola-400x240.jpeg", "source": "https://dailypost.ng/2020/10/"}
